In [1]:
# Imports
# Importo las Bibliotecas que voy a usar en el proyecto
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# DataSources
df = pd.read_csv("data/delitos_2024.csv")

In [3]:
# Functions
# Definición de las funciones quevoy a usar en el proyecto.

def mostrar_valores_unicos(df, columnas):
    for col in columnas:
        print(f"\n{'='*50}")
        print(f"Columna: {col}")
        print(f"{'='*50}")

        conteo = df[col].value_counts(dropna=False)

        for valor, cantidad in conteo.items():
            print(f"{repr(valor)} -> {cantidad}")

# Exploración de datos (DEA)
Luego de haber cargado el dataset, hago una inspección geneal del dataframe buscando validar que sea útil para el TP.
```
Ejemplos
- df.head(), df.info(), df.describe()
- Detección de valores nulos (df.isnull().sum())
```

## Inspección rápida

In [4]:
df.shape # El DataFrame tiene que tener al menos 50K registros y 10 columnaspara este TP

(158838, 15)

In [5]:
# veo la estructura del DataFrame.
# con el datatype puedo completar el diccionario de datos que pide el TP
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 158838 entries, 0 to 158837
Data columns (total 15 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id-mapa   158838 non-null  int64
 1   anio      158838 non-null  int64
 2   mes       158838 non-null  str
 3   dia       158838 non-null  str
 4   fecha     158838 non-null  str
 5   franja    158791 non-null  float64
 6   tipo      158838 non-null  str
 7   subtipo   158838 non-null  str
 8   uso_arma  158838 non-null  str
 9   uso_moto  158838 non-null  str
 10  barrio    154916 non-null  str
 11  comuna    154916 non-null  float64
 12  latitud   155004 non-null  float64
 13  longitud  155004 non-null  float64
 14  cantidad  158838 non-null  int64
dtypes: float64(4), int64(3), str(8)
memory usage: 18.2 MB
None

In [6]:
df.head() # Sin argumentos, el método head() me trae los primeros 5 elementos del DataFrame

,id-mapa,anio,mes,dia,fecha,franja,tipo,subtipo,uso_arma,uso_moto,barrio,comuna,latitud,longitud,cantidad
0,1399612,2024,ENERO,LUNES,2024-01-01,17.0,Robo,Robo total,SI,NO,CHACARITA,15.0,-34.585182,-58.453967,1
1,1399613,2024,ENERO,LUNES,2024-01-01,6.0,Robo,Robo total,SI,NO,CHACARITA,15.0,-34.584186,-58.453476,1
2,1399614,2024,ENERO,LUNES,2024-01-01,1.0,Hurto,Hurto total,NO,NO,MATADEROS,9.0,-34.664360,-58.502121,1
3,1399615,2024,ENERO,LUNES,2024-01-01,19.0,Robo,Robo total,NO,NO,PALERMO,14.0,-34.564851,-58.434855,1
4,1399616,2024,ENERO,LUNES,2024-01-01,20.0,Hurto,Hurto total,NO,NO,SAN NICOLAS,1.0,-34.605522,-58.391176,1

In [7]:
# Obtengo una muestra al azar del DataFrame
df.sample(n=3)

,id-mapa,anio,mes,dia,fecha,franja,tipo,subtipo,uso_arma,uso_moto,barrio,comuna,latitud,longitud,cantidad
50177,1449789,2024,MAYO,LUNES,2024-05-13,13.0,Hurto,Hurto total,NO,NO,BARRACAS,4.0,-34.650405,-58.391468,1
35531,1435143,2024,ABRIL,JUEVES,2024-04-04,0.0,Robo,Robo total,NO,NO,VILLA LUGANO,8.0,-34.672945,-58.470817,1
62818,1462430,2024,JUNIO,DOMINGO,2024-06-16,2.0,Robo,Robo total,NO,SI,RECOLETA,2.0,-34.586714,-58.400033,1

In [8]:
df.tail() # Sin argumentos, el método tail() me trae los últimos 5 elementos del DataFrame

,id-mapa,anio,mes,dia,fecha,franja,tipo,subtipo,uso_arma,uso_moto,barrio,comuna,latitud,longitud,cantidad
158833,1591956,2024,DICIEMBRE,JUEVES,2024-12-12,0.0,Homicidios,Homicidios dolosos,NO,NO,RECOLETA,2.0,-34.595580,-58.408997,1
158834,1591957,2024,DICIEMBRE,DOMINGO,2024-12-15,1.0,Homicidios,Homicidios dolosos,NO,NO,NUEVA POMPEYA,4.0,-34.650123,-58.405448,1
158835,1591958,2024,DICIEMBRE,DOMINGO,2024-12-15,5.0,Homicidios,Homicidios dolosos,NO,NO,CONSTITUCION,1.0,-34.619920,-58.388807,1
158836,1591959,2024,DICIEMBRE,MIERCOLES,2024-12-18,5.0,Homicidios,Homicidios dolosos,NO,NO,BARRACAS,4.0,-34.655290,-58.398290,1
158837,1591960,2024,DICIEMBRE,DOMINGO,2024-12-29,21.0,Homicidios,Homicidios dolosos,NO,NO,PARQUE AVELLANEDA,9.0,-34.646104,-58.469811,1

In [9]:
# Uso 'describe' par ver si, a simple vista, hay algún valor que me llame la atención
# > Datos de latitud/longitud, interesante para un mapa
# > Sólo hay datos de 2024 (min == max == 2024)
df.describe()

,id-mapa,anio,franja,comuna,latitud,longitud,cantidad
count,1.588380e+05,158838.0,158791.000000,154916.000000,1.550040e+05,1.550040e+05,158838.0
mean,1.481333e+06,2024.0,13.056294,7.447591,-1.116540e+13,-3.775561e+12,1.0
std,5.011975e+04,0.0,6.376709,4.601954,1.965873e+15,1.486459e+15,0.0
min,1.399612e+06,2024.0,0.000000,1.000000,-3.464208e+17,-5.852271e+17,1.0
25%,1.439321e+06,2024.0,8.000000,3.000000,-3.463380e+01,-5.846882e+01,1.0
50%,1.479030e+06,2024.0,14.000000,7.000000,-3.461158e+01,-5.843487e+01,1.0
75%,1.518740e+06,2024.0,18.000000,12.000000,-3.459247e+01,-5.840112e+01,1.0
max,1.591960e+06,2024.0,23.000000,15.000000,0.000000e+00,0.000000e+00,1.0

In [10]:
# hay elementos duplicados?
df.duplicated().sum()

np.int64(0)

In [11]:
# recuento de valores únicos que tiene cada columna
df.nunique()

id-mapa     158838
anio             1
mes             12
dia              7
fecha          366
franja          24
tipo             6
subtipo          9
uso_arma         2
uso_moto         2
barrio          48
comuna          15
latitud      92284
longitud     94761
cantidad         1
dtype: int64

## Análisis de columnas y valores

### Columnas de fechas

```text
#   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 1   anio      158838 non-null  int64  
 2   mes       158838 non-null  str    
 3   dia       158838 non-null  str    
 4   fecha     158838 non-null  str    
```

In [12]:
df['anio'].unique()

array([2024])

In [13]:
df['mes'].unique()

<StringArray>
[     'ENERO',    'FEBRERO',      'MARZO',      'ABRIL',       'MAYO',
      'JUNIO',      'JULIO',     'AGOSTO', 'SEPTIEMBRE',    'OCTUBRE',
  'NOVIEMBRE',  'DICIEMBRE']
Length: 12, dtype: str

In [14]:
# Acá hay un problema, si son strings, 'ABRIL' está antes que 'ENERO'.
# Debería ser una variable categórica
# Así como está, puede traerme problemas para para analizar

In [15]:
df['dia'].unique()

<StringArray>
['LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO']
Length: 7, dtype: str

In [16]:
# Con 'dia' tengo el mismo problema que con 'mes': 'JUEVES' está antes que 'LUNES'
# Debería ser una variable categórica
# Así como está, puede traerme problemas para para analizar

In [17]:
df['fecha'].unique()
# trae 366 porque 2024 fue año bisiesto

<StringArray>
['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05',
 '2024-01-06', '2024-01-07', '2024-01-08', '2024-01-09', '2024-01-10',
 ...
 '2024-12-22', '2024-12-23', '2024-12-24', '2024-12-25', '2024-12-26',
 '2024-12-27', '2024-12-28', '2024-12-29', '2024-12-30', '2024-12-31']
Length: 366, dtype: str

In [18]:
# Me conviene convertir la fecha de String a Date
df['fecha'] = pd.to_datetime(df['fecha'])

In [19]:
max = df['fecha'].max()
print ("\nValores minimos y máximos:")
print (f"fecha_min: {df['fecha'].min()}")
print (f"fecha_max: {df['fecha'].max()}")
print ("\nValores posicionales:")
print (f"index 0: {df['fecha'].iloc[0]}")
print (f"index N: {df['fecha'].iloc[-1]}")

Valores minimos y máximos:
fecha_min: 2024-01-01 00:00:00
fecha_max: 2024-12-31 00:00:00

Valores posicionales:
index 0: 2024-01-01 00:00:00
index N: 2024-12-29 00:00:00

In [20]:
# el dataframe no está ordenado por fecha

In [21]:
# RIESGO:
# 'dia' y 'mes' están como string, pero los puedo calcular en base a 'fecha' para que haya consistencia
df['mes'] = df['fecha'].dt.month_name(locale='es_AR')
df['dia'] = df['fecha'].dt.day_name(locale='es_AR')

In [22]:
df['mes']

0             Enero
1             Enero
2             Enero
3             Enero
4             Enero
            ...
158833    Diciembre
158834    Diciembre
158835    Diciembre
158836    Diciembre
158837    Diciembre
Name: mes, Length: 158838, dtype: str

In [23]:
df['dia']

0             Lunes
1             Lunes
2             Lunes
3             Lunes
4             Lunes
            ...
158833       Jueves
158834      Domingo
158835      Domingo
158836    Miércoles
158837      Domingo
Name: dia, Length: 158838, dtype: str

In [24]:
# pero esta conversión tiene el problema de que 'dia' y 'mes' no se convierten en categóricas
#
# Pandas tiene una forma de convertir estas variables categóricas
# Ref: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Categorical.html
# Ref: https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html

In [31]:
# Conversión de los meses a variable categórica (aunque se almacene como string)
df['mes'] = pd.Categorical(
    df['mes'],
    categories=[
        'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
        'Julio', 'Agosto','Septiembre','Octubre','Noviembre', 'Diciembre'
    ],
    ordered=True
)
df['mes']

0             Enero
1             Enero
2             Enero
3             Enero
4             Enero
            ...
158833    Diciembre
158834    Diciembre
158835    Diciembre
158836    Diciembre
158837    Diciembre
Name: mes, Length: 158838, dtype: category
Categories (12, str): ['Enero' < 'Febrero' < 'Marzo' < 'Abril' ... 'Septiembre' < 'Octubre' < 'Noviembre' < 'Diciembre']

In [30]:
# Lo mismo, pero para los días
# Acá, tomo la definición que le primer día de la semana será el LUNES
df['dia'] = pd.Categorical(
    df['dia'],
    categories=['Lunes', 'Martes', 'Miércoles', 'Jueves','Viernes','Sábado','Domingo'],
    ordered=True
)
df['dia']

0             Lunes
1             Lunes
2             Lunes
3             Lunes
4             Lunes
            ...
158833       Jueves
158834      Domingo
158835      Domingo
158836    Miércoles
158837      Domingo
Name: dia, Length: 158838, dtype: category
Categories (7, str): ['Lunes' < 'Martes' < 'Miércoles' < 'Jueves' < 'Viernes' < 'Sábado' < 'Domingo']

In [27]:
df.sample(n=3)

,id-mapa,anio,mes,dia,fecha,franja,tipo,subtipo,uso_arma,uso_moto,barrio,comuna,latitud,longitud,cantidad
127296,1526908,2024,Diciembre,Jueves,2024-12-19,3.0,Hurto,Hurto total,NO,NO,PUERTO MADERO,1.0,-34.617490,-58.362229,1
151299,1584309,2024,Abril,Martes,2024-04-02,19.0,Vialidad,Lesiones por siniestros viales,NO,NO,BALVANERA,3.0,-34.617659,-58.409613,1
52947,1452559,2024,Mayo,Lunes,2024-05-20,12.0,Hurto,Hurto total,NO,NO,SAN NICOLAS,1.0,-34.601872,-58.385671,1

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 158838 entries, 0 to 158837
Data columns (total 15 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id-mapa   158838 non-null  int64
 1   anio      158838 non-null  int64
 2   mes       158838 non-null  category
 3   dia       158838 non-null  category
 4   fecha     158838 non-null  datetime64[us]
 5   franja    158791 non-null  float64
 6   tipo      158838 non-null  str
 7   subtipo   158838 non-null  str
 8   uso_arma  158838 non-null  str
 9   uso_moto  158838 non-null  str
 10  barrio    154916 non-null  str
 11  comuna    154916 non-null  float64
 12  latitud   155004 non-null  float64
 13  longitud  155004 non-null  float64
 14  cantidad  158838 non-null  int64
dtypes: category(2), datetime64[us](1), float64(4), int64(3), str(5)
memory usage: 16.1 MB

### Columnas numéricas

```
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   appid                     89618 non-null  int64  
 3   required_age              89618 non-null  int64  
 4   price                     89618 non-null  float64
 5   dlc_count                 89618 non-null  int64  
 10  metacritic_score          89618 non-null  int64  
 12  achievements              89618 non-null  int64  
 13  recommendations           89618 non-null  int64  
 20  user_score                89618 non-null  int64  
 21  score_rank                39 non-null     float64
 22  positive                  89618 non-null  int64  
 23  negative                  89618 non-null  int64  
 25  average_playtime_forever  89618 non-null  int64  
 26  average_playtime_2weeks   89618 non-null  int64  
 27  median_playtime_forever   89618 non-null  int64  
 28  median_playtime_2weeks    89618 non-null  int64  
 29  discount                  89618 non-null  int64  
 30  peak_ccu                  89618 non-null  int64  
 32  pct_pos_total             89618 non-null  int64  
 33  num_reviews_total         89618 non-null  int64  
 34  pct_pos_recent            89618 non-null  int64  
 35  num_reviews_recent        89618 non-null  int64  
```